[workspace]
members = ["firmware", "simulator"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
description = "A reliable, extensible Watch OS for the PineTime written in Rust"
repository = "https://github.com/Sir-Thomas/patina"
license = "MIT OR Apache-2.0"
publish = false

[patch.crates-io]
lcd-async = { git = "https://github.com/okhsunrog/lcd-async.git", rev = "50efe0a30a4c68a1502049556b2ffb27c13b9539" }
nrf-sdc = { git = "https://github.com/alexmoon/nrf-sdc.git", rev = "2c17fba12fcbf2061e6eeb6834c428aaaa5b4056" }

[profile.release]
debug = 2
codegen-units = 1
lto = "fat"
opt-level = 'z'
