= Bluetooth Low Energy

== Goal

This document will be used to agregate BLE information and to track implementation progress. We will start by implementing the basics, Time Sync, Battery Level, and DFU. After that we will need to decide what BLE services are worth pursuing.

My initial plan was to re-implement all InfiniTime services so the device would "just work" with existing companion apps. I have since changed my mind on this issue. Patina will implement its own services as we see fit. This will give us many advantages as the firmware is developed. Most notably, we do not have to advertise as "InfiniTime". It also allows us to use the simpler secure dfu service for OTA updates. Finally, we will not be restricted in any way as we continue to implement new features.

There is a downside. Since we are not pretending to be running InfiniTime, we will have to write our own companion apps and/or update existing apps that support our device. The flexibility this provides is ultimately worth the tradeoff.

== Services and Characteristics

.Services and Characteristics
|===
| Service | Characteristic | Read | Write | Notify | Implemented | Notes

| Generic Access | Device Name
| x | | | x
| Patina is not supported by GadgetBridge. Hold down on the unsupported device, then select `PineTime (JF Firmware) (Pine64)` to connect

| Generic Access | Appearance
| x | | | x
| 

| Device Information Service | Manufacturer Name String
| x | | | x
| "PINE64"

| Device Information Service | Model Number String
| x | | | x
| "PineTime"

| Device Information Service | Serial Number String
| x | | | x
| "0"

| Device Information Service | Firmware Revision String
| x | | | x
| Patina Version - currently "0.1.0"

| Device Information Service | Hardware Revision String
| x | | | x
| "1.0.0"

| Device Information Service | Software Revision String
| x | | | x
| "patina"

| Current Time Service | Current Time
| | x | | x
| Companion apps can write time to watch. The watch also acts as a client if the device has a CTS server.

| Alert Notification Service | New Alert
| | x | |
| TODO

| Battery Service | Battery Level
| x | | x | 
| TODO: replace dummy value and implement notifications

| Secure DFU Service | DFU Control Point
| | x | x | x
| Notify doesn't seem to be working, but firmware updates work

| Secure DFU Service | DFU Packet
| | x | x | x
| Notify doesn't seem to be working, but firmware updates work

|===