= Flashing Guide
:source-highlighter: highlight.js
:source-language: console

== Preparing your environment

These instructions were tested on PopOS. They should work on any Linux device with minimal adjustments (different commands for installing packages). Rust, probe-rs, and the Python scripts are supported on Windows and Mac OS too, but that will take more work. If you do write scripts for another OS, feel free to submit a pull request.

=== Install required packages
----
sudo usermod -a -G plugdev $USER
sudo apt install rustup libudev-dev libclang-dev just
rustup default stable
rustup target add thumbv7em-none-eabihf
cargo install probe-rs-tools
sudo curl -o /etc/udev/rules.d/69-probe-rs.rules https://probe.rs/files/69-probe-rs.rules
sudo reboot
----
Add the following to ~/.profile
[source,bash]
----
# set PATH so it includes user's cargo bin if it exists
if [ -d "$HOME/.cargo/bin" ] ; then
    PATH="$HOME/.cargo/bin:$PATH"
fi
----

=== Create venv for MCUBoot Image Tool

Copy imgtool.py and the imgtool folder from https://github.com/mcu-tools/mcuboot[MCUboot] to the scripts directory.

----
python3 -m venv .venv
source .venv/bin/activate
pip install -r scripts/requirements.txt
----

== Flashing Patina

If you are not already in the Python venv, run `source .venv/bin/activate` before using any of these scripts.
Commands are run with `Just` use `just --list` to see all available commands

=== just build

Builds an OTA update file that can be flashed to a watch running InfiniTime using any standard companion app.
When flashing a watch running Patina, you will need to use the nRF Connect app.

Output: `images/patina-dfu.zip`

=== just run-mcuboot

Builds an image and uploads it to a development watch using probe-rs

=== just run-baremetal

Same as `run-mcuboot`, but overwrites mcuboot to boot directly into firmware. This speeds up boot time by about 5 seconds.

=== just debug-mcuboot

Builds an image with logs enabled, then uses probe-rs to flash the image and connect to the debug interface.

=== just debug-baremetal

Same as `debug-mcuboot`, but overwrites mcuboot to boot directly into firmware. This speeds up boot time by about 5 seconds.

=== just flash-bootloader

Reflashes the mcuboot bootloader. Bootloader must be placed in `images/bootloader.bin`

=== just sim

Not yet implemented. The goal is to have a simulator to allow for even faster iteration during app development.
